spring:
  application:
    name: CONFIG-SERVER    # Name of the Config Server application

  cloud:
    config:
      server:
        git:
          uri: https://github.com/niteshthakur498/et-config-repo
          clone-on-start: true

server:
  port: 8001  # The port the Config Server will listen on


